money_hack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("cost_api/", include("rest_framework.urls")),
    path("variable_cost/", include("variable_cost.urls"), name="variable_cost"),
]

variable_cost/urls.py
from django.urls import path

from . import views

app_name = "variable_cost"
urlpatterns = [
    path("input", views.InputView.as_view(), name="input"),
    path("list", views.ListView.as_view(), name="list"),
]

variable_cost/forms.py
from django import forms


class InputForm(forms.Form):
    user = forms.CharField(required=True, widget=forms.HiddenInput, initial="10")
    payment_date = forms.DateField(label="支払日", required=True)
    shop = forms.ChoiceField(label="店名", required=True)
    expense = forms.ChoiceField(label="費目", required=True)
    expense_detail = forms.ChoiceField(label="費目詳細", required=False)
    total_amount = forms.IntegerField(
        label="合計金額", required=True, max_value=5000000, min_value=0
    )
    payment_method_1 = forms.ChoiceField(label="支払方法1", required=False)
    payment_detail_1 = forms.ChoiceField(label="支払方法詳細1", required=False)
    amount_1 = forms.IntegerField(
        label="金額1", required=False, max_value=1000000, min_value=0
    )
    payment_method_2 = forms.ChoiceField(label="支払方法2", required=False)
    payment_detail_2 = forms.ChoiceField(label="支払方法詳細2", required=False)
    amount_2 = forms.IntegerField(
        label="金額2", required=False, max_value=1000000, min_value=0
    )
    payment_method_3 = forms.ChoiceField(label="支払方法3", required=False)
    payment_detail_3 = forms.ChoiceField(label="支払方法詳細3", required=False)
    amount_3 = forms.IntegerField(
        label="金額3", required=False, max_value=1000000, min_value=0
    )
    payment_method_4 = forms.ChoiceField(label="支払方法4", required=False)
    payment_detail_4 = forms.ChoiceField(label="支払方法詳細4", required=False)
    amount_4 = forms.IntegerField(
        label="金額4", required=False, max_value=1000000, min_value=0
    )
    payment_method_5 = forms.ChoiceField(label="支払方法5", required=False)
    payment_detail_5 = forms.ChoiceField(label="支払方法詳細5", required=False)
    amount_5 = forms.IntegerField(
        label="金額5", required=False, max_value=1000000, min_value=0
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["payment_date"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "payment-date",}
        )
        self.fields["total_amount"].widget.attrs.update(
            {
                "class": "mdc-text-field__input",
                "aria-labelledby": "total-amount",
                "readonly": True,
            }
        )

        self.fields["payment_method_1"].widget.attrs.update(
            {"class": "sel-payment-method"}
        )
        self.fields["payment_method_2"].widget.attrs.update(
            {"class": "sel-payment-method"}
        )
        self.fields["payment_method_3"].widget.attrs.update(
            {"class": "sel-payment-method"}
        )
        self.fields["payment_method_4"].widget.attrs.update(
            {"class": "sel-payment-method"}
        )
        self.fields["payment_method_5"].widget.attrs.update(
            {"class": "sel-payment-method"}
        )

        self.fields["amount_1"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "amount-1"}
        )
        self.fields["amount_2"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "amount-2"}
        )
        self.fields["amount_3"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "amount-3"}
        )
        self.fields["amount_4"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "amount-4"}
        )
        self.fields["amount_5"].widget.attrs.update(
            {"class": "mdc-text-field__input", "aria-labelledby": "amount-5"}
        )

variable_cost/views.py
from django.views import generic
from django.db import connection, transaction

from .forms import InputForm


class InputView(generic.FormView):
    template_name = "variable_cost/input.html"
    form_class = InputForm
    success_url = "/variable_cost/input"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()

        form = form_class(**self.get_form_kwargs())

        with connection.cursor() as cur:
            # 店舗取得
            sql = """
                SELECT
                    MS.SHOP_CODE
                    , MS.SHOP_NAME
                FROM
                    M_SHOP MS
                LEFT JOIN
                    (SELECT
                        SHOP_CODE
                        , MAX(UPDATE_DATE) AS UPDATE_DATE
                    FROM
                        T_PAYMENT_LIST
                    GROUP BY
                        SHOP_CODE
                    ORDER BY
                        UPDATE_DATE DESC
                    FETCH FIRST 20 ROWS ONLY) TPL
                ON
                    MS.SHOP_CODE = TPL.SHOP_CODE
                ORDER BY
                    TPL.UPDATE_DATE DESC NULLS LAST
                    , MS.SHOP_NAME ASC
                """

            cur.execute(sql)
            form.fields["shop"].choices = cur.fetchall()

            # 費目取得
            sql = """
                SELECT
                    EXPENSE_CODE
                    , EXPENSE_NAME
                FROM
                    M_EXPENSE_CATEGORY
                ORDER BY
                    EXPENSE_CODE ASC
                """

            cur.execute(sql)
            form.fields["expense"].choices = cur.fetchall()

            # 費目詳細取得
            expense_code = (
                self.request.POST["expense"] if "expense" in self.request.POST else "10"
            )

            sql = """
                SELECT
                    E_DETAIL_CODE
                    , E_DETAIL_NAME
                FROM
                    M_E_DETAIL_CATEGORY
                WHERE
                    EXPENSE_CODE = :expense_code
                ORDER BY
                    E_DETAIL_CODE ASC
                """

            params = {"expense_code": expense_code}

            cur.execute(sql, params)
            form.fields["expense_detail"].choices = cur.fetchall()
            form.fields["expense_detail"].choices.insert(0, (None, ""))

            # 支払方法
            sql = """
                SELECT
                    PAYMENT_CODE
                    , PAYMENT_NAME
                FROM
                    M_PAYMENT_METHOD
                ORDER BY
                    PAYMENT_CODE ASC
                """

            cur.execute(sql)
            payment_method = cur.fetchall()

            for i in range(1, 6):
                idx = str(i)

                form.fields["payment_method_" + idx].choices = payment_method

                # 支払方法詳細
                if "payment_method_" + idx in self.request.POST:
                    if self.request.POST["payment_method_" + idx] == "10":
                        sql = ""
                    elif self.request.POST["payment_method_" + idx] == "20":
                        sql = """
                            SELECT
                                CREDIT_CARD_CODE AS CODE
                                , CREDIT_CARD_NAME AS NAME
                            FROM
                                M_CREDIT_CARD
                            ORDER BY
                                CREDIT_CARD_CODE ASC
                            """
                    elif self.request.POST["payment_method_" + idx] == "30":
                        sql = """
                            SELECT
                                GIFT_CERTIFICATE_CODE AS CODE
                                , GIFT_CERTIFICATE_NAME AS NAME
                            FROM
                                M_GIFT_CERTIFICATE
                            ORDER BY
                                GIFT_CERTIFICATE_CODE ASC
                            """
                    elif self.request.POST["payment_method_" + idx] == "40":
                        sql = """
                            SELECT
                                E_MONEY_CODE AS CODE
                                , E_MONEY_NAME AS NAME
                            FROM
                                M_ELECTRONIC_MONEY
                            ORDER BY
                                E_MONEY_CODE ASC
                            """
                    elif self.request.POST["payment_method_" + idx] == "60":
                        sql = """
                            SELECT
                                POINT_CODE AS CODE
                                , POINT_NAME AS NAME
                            FROM
                                M_POINT
                            ORDER BY
                                POINT_CODE ASC
                            """
                    elif self.request.POST["payment_method_" + idx] == "70":
                        sql = """
                            SELECT
                                BANK_CODE AS CODE
                                , BANK_NAME AS NAME
                            FROM
                                M_BANK
                            ORDER BY
                                BANK_CODE ASC
                            """
                    elif self.request.POST["payment_method_" + idx] == "80":
                        sql = """
                            SELECT
                                QR_CODE AS CODE
                                , QR_NAME AS NAME
                            FROM
                                M_QR
                            ORDER BY
                                QR_CODE ASC
                            """

                    if sql != "":
                        cur.execute(sql)
                        form.fields["payment_detail_" + idx].choices = cur.fetchall()

        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

    def form_valid(self, form):
        if "btn-regist" in self.request.POST:
            sql = ""
            params = {}

            try:
                with transaction.atomic():
                    with connection.cursor() as cur:
                        # T_PAYMENT_BREAKDOWN
                        PAYMENT_COLUMNS = {
                            "20": "CREDIT_CARD_CODE",
                            "30": "GIFT_CERTIFICATE_CODE",
                            "40": "E_MONEY_CODE",
                            "60": "POINT_CODE",
                            "70": "BANK_CODE",
                            "80": "QR_CODE",
                        }

                        # SEQ取得
                        sql = """
                            SELECT
                                NVL(MAX(SEQ), 0) + 1 AS NEW_SEQ
                            FROM
                                T_PAYMENT_LIST
                            WHERE
                                PAYMENT_DATE = :payment_date
                            AND SHOP_CODE = :shop_code
                            """

                        params = {
                            "payment_date": form.cleaned_data["payment_date"].strftime(
                                "%Y/%m/%d"
                            ),
                            "shop_code": form.cleaned_data["shop"],
                        }

                        cur.execute(sql, params)

                        row = cur.fetchone()

                        if row is None:
                            result = False
                            message = "Error: Get SEQ"

                        else:
                            new_seq = row[0]

                            # T_PAYMENT_LIST
                            sql = """
                                INSERT INTO
                                    T_PAYMENT_LIST (
                                        PAYMENT_DATE
                                        , SHOP_CODE
                                        , SEQ
                                        , AMOUNT
                                        , EXPENSE_CODE
                                        , E_DETAIL_CODE
                                        , REGIST_USER_CODE
                                        , UPDATE_USER_CODE
                                    ) VALUES (
                                        :payment_date
                                        , :shop_code
                                        , :seq
                                        , :amount
                                        , :expense_code
                                        , :e_detail_code
                                        , :regist_user_code
                                        , :update_user_code
                                    )
                                """

                            params = {
                                "payment_date": form.cleaned_data[
                                    "payment_date"
                                ].strftime("%Y/%m/%d"),
                                "shop_code": form.cleaned_data["shop"],
                                "seq": new_seq,
                                "amount": form.cleaned_data["total_amount"],
                                "expense_code": form.cleaned_data["expense"],
                                "e_detail_code": form.cleaned_data["expense_detail"],
                                "regist_user_code": form.cleaned_data["user"],
                                "update_user_code": form.cleaned_data["user"],
                            }


variable_cost/templates/variable_cost/input.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <link href="{% static 'variable_cost/css/input.bundle.css' %}" rel="stylesheet">
  <title>変動費入力</title>
</head>

<body>
  <header class="mdc-top-app-bar">
    <div class="mdc-top-app-bar__row">
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start">
        <button class="material-icons mdc-top-app-bar__navigation-icon mdc-icon-button"
          aria-label="Open navigation menu">menu</button>
        <span class="mdc-top-app-bar__title">Money Hack</span>
      </section>
      <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-end" role="toolbar">
        <button class="material-icons mdc-top-app-bar__action-item mdc-icon-button" aria-label="Search">search</button>
        <button class="material-icons mdc-top-app-bar__action-item mdc-icon-button"
          aria-label="Options">more_vert</button>
      </section>
    </div>
  </header>
  <div id="contents">
    <form method="POST" action="{% url 'variable_cost:input' %}" id="form-input">
      {% csrf_token %}
      {{ form.user }}
      <div class="mdc-layout-grid">
        <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-field--with-trailing-icon"
              id="mdc-text-payment-date">
              {{ form.payment_date }}
              <i class="material-icons mdc-text-field__icon mdc-text-field__icon--trailing hidden"
                id="payment-date-clear" tabindex="0" role="button">clear</i>
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="payment-date">支払日</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-4">
            {{ form.shop }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.expense }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-3">
            {{ form.expense_detail }}
          </div>
        </div>
        <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_method_1 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_detail_1 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-amount">
              {{ form.amount_1 }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="amount-1">金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <div class="mdc-touch-target-wrapper">
              <button class="mdc-button mdc-button--outlined mdc-button--touch btn-payment-add" type="button"
                data-idx="1">
                <div class="mdc-button__ripple"></div>
                <i class="material-icons mdc-button__icon" aria-hidden="true">add</i>
                <span class="mdc-button__label">追加</span>
                <div class="mdc-button__touch"></div>
              </button>
            </div>
          </div>
        </div>
        <div class="mdc-layout-grid__inner hidden" id="payment-row-2">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_method_2 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_detail_2 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-amount">
              {{ form.amount_2 }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="amount-2">金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <div class="mdc-touch-target-wrapper">
              <button class="mdc-button mdc-button--outlined mdc-button--touch btn-payment-add" type="button"
                data-idx="2">
                <div class="mdc-button__ripple"></div>
                <i class="material-icons mdc-button__icon" aria-hidden="true">add</i>
                <span class="mdc-button__label">追加</span>
                <div class="mdc-button__touch"></div>
              </button>
            </div>
          </div>
        </div>
        <div class="mdc-layout-grid__inner hidden" id="payment-row-3">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_method_3 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_detail_3 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-amount">
              {{ form.amount_3 }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="amount-3">金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <div class="mdc-touch-target-wrapper">
              <button class="mdc-button mdc-button--outlined mdc-button--touch btn-payment-add" type="button"
                data-idx="3">
                <div class="mdc-button__ripple"></div>
                <i class="material-icons mdc-button__icon" aria-hidden="true">add</i>
                <span class="mdc-button__label">追加</span>
                <div class="mdc-button__touch"></div>
              </button>
            </div>
          </div>
        </div>
        <div class="mdc-layout-grid__inner hidden" id="payment-row-4">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_method_4 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_detail_4 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-amount">
              {{ form.amount_4 }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="amount-4">金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <div class="mdc-touch-target-wrapper">
              <button class="mdc-button mdc-button--outlined mdc-button--touch btn-payment-add" type="button"
                data-idx="4">
                <div class="mdc-button__ripple"></div>
                <i class="material-icons mdc-button__icon" aria-hidden="true">add</i>
                <span class="mdc-button__label">追加</span>
                <div class="mdc-button__touch"></div>
              </button>
            </div>
          </div>
        </div>
        <div class="mdc-layout-grid__inner hidden" id="payment-row-5">
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_method_5 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            {{ form.payment_detail_5 }}
          </div>
          <div class="mdc-layout-grid__cell mdc-layout-grid__cell--span-2">
            <label class="mdc-text-field mdc-text-field--outlined mdc-text-amount">
              {{ form.amount_5 }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="amount-5">金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
        </div>
        <div class="mdc-layout-grid__inner">
          <div class="mdc-layout-grid__cell">
            <label class="mdc-text-field mdc-text-field--outlined" id="mdc-text-total-amount">
              {{ form.total_amount }}
              <span class="mdc-notched-outline">
                <span class="mdc-notched-outline__leading"></span>
                <span class="mdc-notched-outline__notch">
                  <span class="mdc-floating-label" id="total-amount">合計金額</span>
                </span>
                <span class="mdc-notched-outline__trailing"></span>
              </span>
            </label>
          </div>
          <div class="mdc-layout-grid__cell">
            <div class="mdc-touch-target-wrapper">
              <button class="mdc-button mdc-button--raised mdc-button--touch" type="submit" name="btn-regist">
                <div class="mdc-button__ripple"></div>
                <span class="mdc-button__label">登録</span>
                <div class="mdc-button__touch"></div>
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
  <script src="{% static 'variable_cost/js/input.bundle.js' %}"></script>
</body>

</html>

variable_cost/templates/variable_cost/list.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <link href="{% static 'variable_cost/css/list.bundle.css' %}" rel="stylesheet">
  <title>変動費一覧</title>
</head>

<body>
  <table>
    <thead>
      <th>支払日</th>
      <th>店舗</th>
      <th>金額</th>
    </thead>
    <tbody>
      {% for cost in cost_list %}
      <tr>
        <td>{{ cost.payment_date }}</td>
        <td>{{ cost.shop_name }}</td>
        <td>{{ cost.amount }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <script src="{% static 'variable_cost/js/list.bundle.js' %}"></script>
</body>

</html>